// PM2 Ecosystem file for managing backend and frontend processes
module.exports = {
  apps: [
    {
      name: 'hirepy-backend',
      script: 'backend/venv/Scripts/python.exe',
      args: '-m uvicorn app.main:app --host 127.0.0.1 --port 8000',
      cwd: 'C:/recent/hirepy/hirepy/backend',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        ENVIRONMENT: 'production',
        DEBUG: 'false',
      },
      error_file: './logs/pm2-backend-error.log',
      out_file: './logs/pm2-backend-out.log',
      log_file: './logs/pm2-backend-combined.log',
      time: true,
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
    {
      name: 'hirepy-frontend',
      script: 'server.js',
      cwd: 'C:/recent/hirepy/hirepy/frontend',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
      },
      error_file: './logs/pm2-frontend-error.log',
      out_file: './logs/pm2-frontend-out.log',
      log_file: './logs/pm2-frontend-combined.log',
      time: true,
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
  ],
};

